on:
  pull_request:
    types: [opened, synchronize, review_requested]

jobs:
  pr_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT review code
    steps:
      - name: ChatGTP review code
        uses: satindra75/chatgpt-github-actions@v1.11
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_engine: "text-davinci-003" #optional
          #openai_engine: "gpt-3.5-turbo" #optional
          openai_temperature: 0.5 #optional
          openai_max_tokens: 2048 #optional
          mode: files 
